### ISSUE TITLE
缩放大小错误

### ISSUE THREAD

**Issue by sdjge** [mo-jinran/BGEnhanced-Extra#1]
全部设置均为默认
安装了NCM市场大部分插件（应该说是几乎所有了）

出现问题为
当我最大化窗口，将鼠标光标从网易云窗口移动到任务栏时（网易云未最小化或被其他窗口覆盖），背景会缩放至非常小（应该是十分之一左右）但是切换窗口后恢复正常

附件为录屏
[Uploading 2023-05-26_10-20-38.zip…]()

**Comment by sdjge** [comment]
发现问题所在，是更新导致某些参数变成错误参数了，然后我还没设置成默认（坏了尴尬了

**Comment by mo-jinran** [comment]
xwx 我把默认单位改成百分比了，之前是无单位数字
